config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    resources :notices, only: :index
    resources :inquiries, only: [:new, :create]
    resource :users, only: [:show, :edit, :update]
  end

  devise_for :users, :controllers =>{
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  root to: "public/homes#top"
  get "homes/stand_by" => 'public/homes#stand_by', as: 'stand_by'
  get "homes/rankup" => 'public/homes#rankup', as: 'rankup'

  get "question_rooms/match_make" => 'public/question_rooms#match_make', as: 'match_make'
  get "question_rooms/battle" => 'public/question_rooms#battle', as: 'battle'
  get "question_rooms/finish" => 'public/question_rooms#finish', as: 'finish'
  get "question_rooms/result" => 'public/question_rooms#result', as: 'result'
  get "question_rooms/get_all_answers_of" => 'public/question_rooms#get_all_answers_of', as: 'get_all_answers_of'

  get "users/confirm" => 'public/users#confirm', as: 'confirm'
  patch "users/withdraw" => 'public/users#withdraw', as: 'withdraw'

  post "follows/follow" => 'public/follows#follow', as: 'follow'
  get "follows/toggle" => 'public/follows#toggle', as: 'follow_toggle'

  devise_for :admin, :controllers =>{
    :sessions => 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/homes/top' => 'homes#top'
    post '/homes/search' => 'homes#search'
    resources :users, only: [:edit, :update, :index, :show]
    resources :question_rooms, except: [:destroy]
    resources :inquiries, only: [:update, :index, :show, :edit]
  end

  mount ActionCable.server => '/cable'

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user

  attribute :is_readed, :boolean, default: false
  attribute :is_solved, :boolean, default: false

  validates :user_id, :title, :body, presence: true
end

app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < ApplicationController
  before_action :signed_in_check
  
  def signed_in_check
    if !admin_signed_in?
      redirect_to new_admin_session_path
    end
  end
  
  def index
    @inquiries = Inquiry.all.order("created_at DESC")
  end

  # お問い合わせ詳細画面
  def show
  # 処理内容
  # 表示されたお問い合わせを既読(is_readed: true)にする
    
    @inquiry = Inquiry.find(params[:id])
    @inquiry.update(is_readed: true)
  end

  def edit
    @inquiry = Inquiry.find(params[:id])
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.update(inquiry_params)
      redirect_to admin_inquiry_path(@inquiry.id)
    else
      render :edit
    end
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:is_solved)
  end
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/views/admin/inquiries/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10">
      <h1>お問い合わせ詳細</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <%= form_with model:@inquiry, url: "/admin/inquiries/#{@inquiry.id}", local: true do |f| %>
        <table class="table">
          <tr>
            <th>お問い合わせ日時</th>
            <td><%= l @inquiry.created_at %></td>
          </tr>
          <tr>
            <th>ユーザ名/ユーザid</th>
            <td><%= User.find(@inquiry.user_id).name %>/<%= @inquiry.user_id %></td>
          </tr>
          <tr>
            <th>件名</th>
            <td><%= @inquiry.title %></td>
          </tr>
          <tr>
            <th>お問い合わせ内容</th>
            <td><%= @inquiry.body %></td>
          </tr>
          <tr>
            <th>解決/未解決</th>
            <td>
              <div class="row form-group form-inline">
                <%= f.radio_button :is_solved, true %>解決済み<label> </label><%= f.radio_button :is_solved, false %>未解決
              </div>
            </td>
          </tr>
          <tr>
            <td><%= f.submit '変更する' %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/inquiries/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10">
      <h1>問い合わせ一覧</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <table class="table">
        <tr>
          <th>問い合わせ日時</th>
          <th>ユーザ名/id</th>
          <th>件名</th>
        </tr>
        <% @inquiries.each do |inquiry| %>
          <tr>
            <td><%= l inquiry.created_at %></td>
            <td><%= User.find(inquiry.user_id).name %>/<%= inquiry.user_id %></td>
            <td><%= link_to inquiry.title, admin_inquiry_path(inquiry.id) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/inquiries/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10">
      <h1>お問い合わせ詳細</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <table class="table">
        <tr>
          <th>お問い合わせ日時</th>
          <td><%= l @inquiry.created_at %></td>
        </tr>
        <tr>
          <th>ユーザ名/ユーザid</th>
          <td><%= User.find(@inquiry.user_id).name %>/<%= @inquiry.user_id %></td>
        </tr>
        <tr>
          <th>件名</th>
          <td><%= @inquiry.title %></td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td><%= @inquiry.body %></td>
        </tr>
        <tr>
          <th>解決/未解決</th>
          <td>
            <% if @inquiry.is_solved %>
              <label>解決済み</label>
            <% else %>
              <label>未解決</label>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <%= link_to '編集する', edit_admin_inquiry_path(@inquiry.id) %>
    </div>
  </div>
</div>