config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    resources :notices, only: :index
    resources :inquiries, only: [:new, :create]
    resource :users, only: [:show, :edit, :update]
  end

  devise_for :users, :controllers =>{
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  root to: "public/homes#top"
  get "homes/stand_by" => 'public/homes#stand_by', as: 'stand_by'
  get "homes/rankup" => 'public/homes#rankup', as: 'rankup'

  get "question_rooms/match_make" => 'public/question_rooms#match_make', as: 'match_make'
  get "question_rooms/battle" => 'public/question_rooms#battle', as: 'battle'
  get "question_rooms/finish" => 'public/question_rooms#finish', as: 'finish'
  get "question_rooms/result" => 'public/question_rooms#result', as: 'result'
  get "question_rooms/get_all_answers_of" => 'public/question_rooms#get_all_answers_of', as: 'get_all_answers_of'

  get "users/confirm" => 'public/users#confirm', as: 'confirm'
  patch "users/withdraw" => 'public/users#withdraw', as: 'withdraw'

  post "follows/follow" => 'public/follows#follow', as: 'follow'
  get "follows/toggle" => 'public/follows#toggle', as: 'follow_toggle'

  devise_for :admin, :controllers =>{
    :sessions => 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/homes/top' => 'homes#top'
    post '/homes/search' => 'homes#search'
    resources :users, only: [:edit, :update, :index, :show]
    resources :question_rooms, except: [:destroy]
    resources :inquiries, only: [:update, :index, :show, :edit]
  end

  mount ActionCable.server => '/cable'

end

app/models/question_room.rb
class QuestionRoom < ApplicationRecord
  DEFAULT_GAME_TIME = 120 #デフォルトの対決時間[秒]

  belongs_to :admin, foreign_key: :added_by
  has_many :panelists
  has_many :answers

  enum room_status: {standby: 0, matching: 1, running: 2, finished: 3}

  attribute :game_time, :integer, default: DEFAULT_GAME_TIME
  attribute :total_answer_count, :integer, default: 0
  attribute :total_nice_count, :integer, default: 0
  attribute :is_active, :boolean, default: true
  attribute :is_set, :boolean, default: false
  attribute :room_status, :integer, default: :standby
  attribute :question_room_set_id, :integer, default: -1

  validates :body, :added_by, presence: true

  # 待機状態にさせる
  def get_ready
    # 自身の処理
    self.update(is_active: true, is_set: false, room_status: :standby)
    # 紐づくPanelistを削除
    panelists = Panelist.where(question_room_id: self.id)
    if panelists.count != 0
      panelists.each do |panelist|
        panelist.destroy()
      end
    end
  end
end

app/controllers/admin/question_rooms_controller.rb
class Admin::QuestionRoomsController < ApplicationController
  before_action :signed_in_check
  
  def signed_in_check
    if !admin_signed_in?
      redirect_to new_admin_session_path
    end
  end

  def new
    @question_room = QuestionRoom.new()
  end

  def create
    @question_room = QuestionRoom.new(question_room_params)
    @question_room.added_by = current_admin.id

    if @question_room.save
      redirect_to admin_question_room_path(@question_room.id)
    else
      render :new
    end
  end

  def edit
    @question_room = QuestionRoom.find(params[:id])
  end

  def update
    @question_room = QuestionRoom.find(params[:id])
    if @question_room.update(question_room_params)
      redirect_to admin_question_room_path(params[:id])
    else
      render :edit
    end
  end

  def show
    @question_room = QuestionRoom.find(params[:id])
  end

  def index
    @question_rooms = QuestionRoom.all
  end

  private

  def question_room_params
    params.require(:question_room).permit(:body, :is_active, :is_set)
  end

end

app/helpers/admin/question_rooms_helper.rb
module Admin::QuestionRoomsHelper
end

app/views/admin/question_rooms/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10">
      <h1>お題編集</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <%= form_with model: @question_room, url: "/admin/question_rooms/#{@question_room.id}", local: true do |f| %>
        <div class="form-group row">
          <label class="col-lg-3">お題</label>
          <%= f.text_field :body, class:"col-lg-5" %>
        </div>
        <div class="form-group row form-inline">
          <div class="col-lg-3">
            <label class="d-block">お題ステータス</label>
            <p>無効にすると対戦に使用されなくなります。</p>
          </div>
          <%= f.radio_button :is_active, true %>有効<label> </label><%= f.radio_button :is_active, false %>無効
        </div>
        <div class="row">
          <%= f.submit '変更を保存' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/question_rooms/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10">
      <h1>お題一覧画面</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8">
      <table class="table">
        <tr>
          <th>お題</th>
          <th>作成者</th>
          <th>作成日</th>
          <th>回答者1</th>
          <th>回答者2</th>
        </tr>
      <% @question_rooms.each do |qr| %>
        <tr>
          <td><%= link_to qr.body, admin_question_room_path(qr.id) %></td>
          <td><%= Admin.find(qr.added_by).name %></td>
          <td><%= l qr.created_at, format: :japan %></td>
          <% panelists = qr.panelists.all %>
          <% panelists.each do |panelist| %>
            <td><%= User.find(panelist.user_id).name %></td>
          <% end %>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/question_rooms/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10 mx-auto d-flex justify-content-center">
      <h1>お題追加</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <%= render partial: 'templates/error', locals: {model: @question_room} %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-8 d-flex justify-content-center">
      <%= form_with model: @question_room, url: '/admin/question_rooms', local: true do |f| %>
        <div class="row form-group">
          <label class="col-lg-3">お題</label>
          <%= f.text_field :body, class: "col-lg-9", placeholder: '(例) こんなドラえもんは嫌だ。どんなの？' %>
        </div>
        <div class="form-group row form-inline">
          <%= f.radio_button :is_active, true, checked: true %>有効<label> </label><%= f.radio_button :is_active, false %>無効
        </div>
        <div class="row justify-content-center">
          <%= f.submit '作成する' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/question_rooms/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10">
      <h1>お題詳細</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <table class="table table-borderless">
        <tr>
          <th>お題</th>
          <td><p><%= @question_room.body %></p></td>
        </tr>
        <tr>
          <th>作成者</th>
          <td><%= current_admin.name %></td>
        </tr>
        <tr>
          <th>作成日/更新日</th>
          <td><p><%= l @question_room.created_at, format: :japan %> / <%= l @question_room.updated_at, format: :japan %></p></td>
        </tr>
        <tr>
          <th>お題ステータス</th>
          <td>
            <% if @question_room.is_active %>
              <label>有効</label>
            <% else %>
              <label>無効</label>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>出題ステータス</th>
          <td>
            <% if @question_room.is_set %>
              <label>出題済み</label>
            <% else %>
              <label>未出題</label>
            <% end %>
          </td>
        </tr>
        <% if @question_room.is_set %>
          <% count = 1 %>
          <% panelists = Panelist.where(question_room_id: @question_room.id) %>
          <% panelists.each do |panelist| %>
            <tr>
              <th><label>参加者<%= "#{count}" %></label></th>
              <td><%= render partial: 'templates/user_name', locals: {user: User.find(panelist.user_id), url: ""} %></td>
            </tr>
            <% count += 1 %>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8">
      <h2>回答一覧</h2>
      <% if @question_room.answers.count == 0 %>
        <p>回答はまだありません。</p>
      <% else %>
        <table class="table">
          <tr>
            <th>回答</th>
            <th>回答者</th>
          </tr>
          <% @question_room.answers.all.each do |answer| %>
            <tr>
              <td><div><%= answer.body %></div></td>
              <td><div><%= User.find(answer.user_id).name %></div></td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <div><%= link_to '編集する', edit_admin_question_room_path(@question_room.id) %></div>
    </div>
  </div>
</div>