config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    resources :notices, only: :index
    resources :inquiries, only: [:new, :create]
    resource :users, only: [:show, :edit, :update]
  end

  devise_for :users, :controllers =>{
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  root to: "public/homes#top"
  get "homes/stand_by" => 'public/homes#stand_by', as: 'stand_by'
  get "homes/rankup" => 'public/homes#rankup', as: 'rankup'

  get "question_rooms/match_make" => 'public/question_rooms#match_make', as: 'match_make'
  get "question_rooms/battle" => 'public/question_rooms#battle', as: 'battle'
  get "question_rooms/finish" => 'public/question_rooms#finish', as: 'finish'
  get "question_rooms/result" => 'public/question_rooms#result', as: 'result'
  get "question_rooms/get_all_answers_of" => 'public/question_rooms#get_all_answers_of', as: 'get_all_answers_of'

  get "users/confirm" => 'public/users#confirm', as: 'confirm'
  patch "users/withdraw" => 'public/users#withdraw', as: 'withdraw'

  post "follows/follow" => 'public/follows#follow', as: 'follow'
  get "follows/toggle" => 'public/follows#toggle', as: 'follow_toggle'

  devise_for :admin, :controllers =>{
    :sessions => 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/homes/top' => 'homes#top'
    post '/homes/search' => 'homes#search'
    resources :users, only: [:edit, :update, :index, :show]
    resources :question_rooms, except: [:destroy]
    resources :inquiries, only: [:update, :index, :show, :edit]
  end

  mount ActionCable.server => '/cable'

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :signed_in_check, only: [:search]
  
  def signed_in_check
    if !admin_signed_in?
      redirect_to new_admin_session_path
    end
  end
  
  def top
    @question_rooms = QuestionRoom.all.order("created_at DESC")
  end
  
  # 検索結果画面
  def search
    # 検索対象は「回答者名」「回答」「お題」
    # 検索は部分一致で行う
    
    key = params[:search]
    
    # 回答者名
    @users = User.where("name LIKE ?", "%#{key}%")
    
    # 回答
    @answers = Answer.where("body LIKE ?", "%#{key}%")
    
    # お題
    @question_rooms = QuestionRoom.where("body LIKE ?", "%#{key}%")
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/search.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-10">
      <h1>検索結果</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <h2>ユーザー(<%= @users.count %>件)</h2>
      <% @users.each do |user| %>
        <div><%= link_to user.name, admin_user_path(user.id) %></div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <h2>お題(<%= @question_rooms.count %>件)</h2>
      <% @question_rooms.each do |question_room| %>
        <div><%= link_to question_room.body, admin_question_room_path(question_room.id) %></div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
      <h2>回答(<%= @answers.count %>件)</h2>
        <% @answers.each do |answer| %>
        <div><%= link_to answer.body, admin_question_room_path(answer.question_room_id) %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
      <h1>お題一覧</h1>
    </div>
    <div class="col-lg-3">
      <h2><%= link_to '＋', new_admin_question_room_path %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8">
      <table class="table">
        <% @question_rooms.each do |qr| %>
          <tr>
            <%= link_to qr.body, admin_question_room_path(qr.id) %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>