config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    resources :notices, only: :index
    resources :inquiries, only: [:new, :create]
    resource :users, only: [:show, :edit, :update]
  end

  devise_for :users, :controllers =>{
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  root to: "public/homes#top"
  get "homes/stand_by" => 'public/homes#stand_by', as: 'stand_by'
  get "homes/rankup" => 'public/homes#rankup', as: 'rankup'

  get "question_rooms/match_make" => 'public/question_rooms#match_make', as: 'match_make'
  get "question_rooms/battle" => 'public/question_rooms#battle', as: 'battle'
  get "question_rooms/finish" => 'public/question_rooms#finish', as: 'finish'
  get "question_rooms/result" => 'public/question_rooms#result', as: 'result'
  get "question_rooms/get_all_answers_of" => 'public/question_rooms#get_all_answers_of', as: 'get_all_answers_of'

  get "users/confirm" => 'public/users#confirm', as: 'confirm'
  patch "users/withdraw" => 'public/users#withdraw', as: 'withdraw'

  post "follows/follow" => 'public/follows#follow', as: 'follow'
  get "follows/toggle" => 'public/follows#toggle', as: 'follow_toggle'

  devise_for :admin, :controllers =>{
    :sessions => 'admin/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/homes/top' => 'homes#top'
    post '/homes/search' => 'homes#search'
    resources :users, only: [:edit, :update, :index, :show]
    resources :question_rooms, except: [:destroy]
    resources :inquiries, only: [:update, :index, :show, :edit]
  end

  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OgiriChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container-fluid header-container">
        <nav class= "navbar navbar-expand-lg navbar-light">
          <h1 class="navbar-brand">
            <% if !user_signed_in? && !admin_signed_in? %>
              <%= link_to 'OgiriChat', root_path %>
            <% elsif user_signed_in? && !admin_signed_in? %>
              <%= link_to 'OgiriChat', root_path %>
            <% elsif !user_signed_in? && admin_signed_in? %>
              <%= link_to 'OgiriChat', admin_homes_top_path %>
            <% else %>
              <label>ダブルログインが発生しています(ユーザand開発者)</label>
            <% end %>
          </h1>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-target" aria-controls="nav-target" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon navbar__icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="nav-target">
            <ul class="navbar-nav ml-auto">
              <!--未ログイン時-->
              <% if !user_signed_in? && !admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to '新規登録', new_user_registration_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ログイン', new_user_session_path, class:"nav-link" %>
                </li>

              <!--ユーザのみログイン時-->
              <% elsif user_signed_in? && !admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'マイページ', users_path, class:"nav-link" %>
                </li>
                <% if current_user.notices.where(is_readed: false).count == 0 %>
                  <li class="nav-item navbar__notice--default">
                    <%= link_to '通知', notices_path, class:"nav-link" %>
                  </li>
                <% else %>
                  <li class="nav-item navbar__notice--unread">
                    <%= link_to '通知', notices_path, class:"nav-link" %>
                  </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to '問い合わせ', new_inquiry_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link" %>
                </li>

              <!--管理者ログイン時-->
              <% elsif !user_signed_in? && admin_signed_in? %>
                <li class="nav-item">
                  <%= form_with url: admin_homes_search_path, method: :post, local: true do |f| %>
                    <%= f.text_field :search %>
                    <%= f.submit '検索' %>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to 'お題ルーム一覧', admin_question_rooms_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ユーザー一覧', admin_users_path, class:"nav-link" %>
                </li>
                <% if Inquiry.where(is_readed: false).count == 0 %>
                  <li class="nav-item  navbar__inquiry--default">
                    <%= link_to '問い合わせ一覧', admin_inquiries_path, class:"nav-link" %>
                  </li>
                <% else %>
                  <li class="nav-item  navbar__inquiry--unread">
                    <%= link_to '問い合わせ一覧', admin_inquiries_path, class:"nav-link" %>
                  </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"nav-link" %>
                </li>
              <% else %>
                <li><label>ダブルログインが発生しています!!</label></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>